[package]
name = "autoadb"
version = "0.1.0"
authors = ["Romain Vimont <rom@rom1v.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
byteorder = "1.3"
